#!/usr/bin/env python3
"""Write or verify the identity of one reviewed kongctl plan artifact."""

import hashlib
import json
import os
import sys
from datetime import datetime, timezone
from pathlib import Path

CLI_VERSION = "1.16.0"
BASE_URL = "https://us.api.konghq.com"
ORG_ID = "bc68a981-db50-43b4-a6bc-6a3ab0557d3c"
NAMESPACE = "summit-ai-demo"
MAX_AGE_SECONDS = 24 * 60 * 60


def fail(message):
    raise SystemExit(message)


def identity():
    return {
        "source_sha": os.environ["GITHUB_SHA"],
        "profile": "default",
        "base_url": BASE_URL,
        "organization_id": ORG_ID,
        "namespace": NAMESPACE,
        "kongctl_version": CLI_VERSION,
    }


def validate_plan(plan):
    metadata = plan.get("metadata", {})
    summary = plan.get("summary", {})
    if metadata.get("mode") != "apply":
        fail("Saved plan is not in apply mode")
    if metadata.get("generator", "") != f"kongctl/{CLI_VERSION}":
        fail("Saved plan was generated by an unexpected kongctl version")
    if summary.get("by_action", {}).get("DELETE", 0):
        fail("Saved plan contains deletions")
    if summary.get("total_changes") != len(plan.get("changes", [])):
        fail("Saved plan summary and changes disagree")
    generated_at = metadata.get("generated_at", "")
    try:
        generated_time = datetime.fromisoformat(generated_at.replace("Z", "+00:00"))
        age = (datetime.now(timezone.utc) - generated_time).total_seconds()
    except (ValueError, TypeError):
        fail("Saved plan has no valid generation time")
    if age < -60 or age > MAX_AGE_SECONDS:
        fail("Saved plan is older than 24 hours or has a future timestamp")


def main():
    if len(sys.argv) != 2 or sys.argv[1] not in {"write", "verify"}:
        fail("Usage: plan-audit.py write|verify")
    audit = Path("audit")
    plan_path = audit / "plan.json"
    manifest_path = audit / "manifest.json"
    plan_bytes = plan_path.read_bytes()
    plan = json.loads(plan_bytes)
    validate_plan(plan)
    digest = hashlib.sha256(plan_bytes).hexdigest()

    if sys.argv[1] == "write":
        manifest = identity() | {
            "run_id": os.environ["GITHUB_RUN_ID"],
            "run_attempt": os.environ["GITHUB_RUN_ATTEMPT"],
            "plan_sha256": digest,
            "generated_at": plan["metadata"]["generated_at"],
            "summary": plan["summary"],
        }
        manifest_path.write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n")
        with open(os.environ["GITHUB_OUTPUT"], "a", encoding="utf-8") as output:
            output.write(f"plan_sha256={digest}\n")
        print("Saved plan SHA-256:", digest)
        return

    manifest = json.loads(manifest_path.read_text())
    expected = os.environ.get("EXPECTED_PLAN_SHA256", "")
    if not expected or digest != expected or manifest.get("plan_sha256") != expected:
        fail("Saved plan digest does not match the reviewed plan job output")
    for key, value in identity().items():
        if manifest.get(key) != value:
            fail(f"Saved plan {key} does not match this run and target")
    if manifest.get("run_id") != os.environ.get("EXPECTED_PLAN_RUN_ID"):
        fail("Saved plan run ID does not match the approved plan run")
    if manifest.get("run_attempt") != os.environ.get("EXPECTED_PLAN_RUN_ATTEMPT"):
        fail("Saved plan attempt does not match the approved plan run")
    if manifest.get("generated_at") != plan["metadata"]["generated_at"]:
        fail("Saved plan generation time differs from audit manifest")
    if manifest.get("summary") != plan["summary"]:
        fail("Saved plan summary differs from the audit manifest")
    print("Reviewed plan identity and 24-hour age verified:", digest)


if __name__ == "__main__":
    main()
